### ISSUE TITLE
Question: Are Crosshairs expected to work with the Categorized Bar Chart?

### ISSUE THREAD

**Issue by optio50** [domarm-comat/pglive#10]
Are Crosshairs expected to work with the Categorized Bar Chart?

I think I would only need it for the Date Time Axis to see preciously when the state changed happened.

**Comment by domarm-comat** [comment]
Yes, Crosshairs should work. Just use it as with any other LivePlot. Give it a try.
You can expect text in format:
X: formatted_x_point
Y: category_name

Crosshairs are written in general to always display X: value and Y: value. Format is controlled with Axis.TICK_FORMAT attribute for LiveAxis. In the future I will add option to make it more customized, for example just to show X or Y. But in current implementation it's always both X and Y.

PS: Thanks for your generous support. It's greatly appreciated! :+1:

**Comment by optio50** [comment]
Opps, Yeah I forgot the **kwargs.

Thanks for a really cool program!
