### ISSUE TITLE
Question: Autoscale plots when legend item is turned off

### ISSUE THREAD

**Issue by optio50** [domarm-comat/pglive#11]
I cant determine if this is a pyqtgraph function or PGlive.

A graph with multiple plots and a legend.
If you click an item in the legend box its plot is turned off in the graph. (its still collecting data)

What I have is three plots with what can be large variations in Y axis values.
I was hoping to autorange the remaining plots when a plot is turned off from the legend.
For example below. Turn off Watts and have Volts and Amps auto scale for best viewable resolution.
![legend-plots](https://user-images.githubusercontent.com/4461936/198852776-c2f24631-dc81-48d3-a232-321c2deb7931.png)

**Comment by domarm-comat** [comment]
This is issue of pglive and LiveAxisRange. Issue was, that plot was used in autorange calculation when it was hidden.
This should be fixed in version 0.5.4.

**Comment by optio50** [comment]
Confirmed Fixed!
PGlive gets more exciting all the time.

Thanks for the quick fix :-)
