### ISSUE TITLE
LiveAxisRange Multiple Plots Auto range if plot turned off.

### ISSUE THREAD

**Issue by optio50** [domarm-comat/pglive#12]
Is LiveAxisRange supposed to work with multiple plots?
if you turn one of the plots off with the legend the "A" autorange breaks and plots disappear.

        PV1watts_plot = LiveLinePlot(pen='orange',name='PV-1',fillLevel=0, brush=(213,129,44,100))
        PV2watts_plot = LiveLinePlot(pen='cyan',name='PV-2', fillLevel=0, brush=(102,102,255,100))

        # Data connectors for each plot with dequeue of max_points
        self.PV1watts_connector = DataConnector(PV1watts_plot, max_points=48000) 
        self.PV2watts_connector = DataConnector(PV2watts_plot, max_points=48000) 

        # Setup bottom axis with TIME tick format
        # use Axis.DATETIME to show date
        pv1_watts_bottom_axis = LiveAxis("bottom", **{Axis.TICK_FORMAT: Axis.TIME})

        # Create plot
        self.PV1_graph_Widget = LivePlotWidget(title="Charger 1 & 2 Watts 1 Hour of 24",
        axisItems={'bottom': pv1_watts_bottom_axis},
        x_range_controller=LiveAxisRange(roll_on_tick=1800, offset_left=1), **kwargs)

        self.PV1_graph_Widget.x_range_controller.crop_left_offset_to_data = True
        
      
        # Show grid
        self.PV1_graph_Widget.showGrid(x=True, y=True, alpha=0.3)

        # Set labels
        self.PV1_graph_Widget.setLabel('bottom')
        self.PV1_graph_Widget.setLabel('left', 'Watts')

        self.PV1_graph_Widget.addLegend() # If plot is named, auto add name to legend

        # Add Line
        self.PV1_graph_Widget.addItem(PV1watts_plot)
        self.PV1_graph_Widget.addItem(PV2watts_plot)

        # Add chart to Layout in Qt Designer
        self.PV1_Watts_Layout.addWidget(self.PV1_graph_Widget)

**Comment by domarm-comat** [comment]
Ok, I can reproduce the issue. I think in your previous question I was addressing turning axis On and Off. I was just disabling hidden axis from autorange. That might be the source of this issue. I'm a bit more busy these days, but I will have a look at it soon.

**Comment by optio50** [comment]
No hurry. Thanks for your time and attention.

**Comment by domarm-comat** [comment]
Thanks for your patience!
I looked into this problem and it was related to previous "fix" with hiding and showing subplots using legend.

I had to do more substantial update. Pglive is now updating data when subplot is hidden. No data is ignored that way, but when plot is hidden, DataBound of hidden plot is ignored and only visible subplots are considered in final x and y DataBound calculation.

Hopefully this update (v0.5.5) will solve your issue.

Please check your app more thoroughly, to confirm that nothing else was broken with this update.

**Comment by optio50** [comment]
Been checking it out for a few days now.
Everything seems just as it should be.

Thanks for taking the time to do these things.
I know your time is valuable and I appreciate your efforts.
 :-)
