### ISSUE TITLE
Question: If using "Promoted Widget", How to add LivePlotWidget(title=...., axisItems=......, **kwargs)

### ISSUE THREAD

**Issue by optio50** [domarm-comat/pglive#13]
I don't normally use a promoted widget but thought I would try it out in QT Designer.
Normally I create the widget manually.
If it's promoted and created in the QT Designer how do I add,
LivePlotWidget(title="Chart Title", axisItems={'bottom': bottom_axis}, **kwargs)

I can add title with .setLabels
I can add axisItems with .setAxisItems

Those are done with pyqtgraph options.
How do I add ** kwargs that recognize the pglive crosshairs?

Can it all be done with a one liner like I normally do with a widget created manually?

I know you're busy. Thanks for looking.

**Comment by domarm-comat** [comment]
Qt is using property system to add additional properties to the widget after widget creation. In designer, you can do it by adding dynamic property:

![Qt Designer_008](https://user-images.githubusercontent.com/95224199/203819481-cece9186-8e52-4a5d-bb2d-a5a6f535e4fa.png)

However pyqtgraph doesn't support this approach and therefore it's not possible in pglive. It would be quite a lot of work to implement and wrap every property to be compatible with get / set property system of Qt. Each property name would have to be checked and bind with it's function call in pyqtgraph. Also it's not possible to pass lists, tuples or dicts from designer, only static types such as string, int, bool, ..., so many properties won't work and would need some workaround to implement. It would make everything much more complex with big room for bugs and mistakes...

**Comment by optio50** [comment]
Thanks for explaining.
 I was just wondering, not wanting you to change anything. :-)
