### ISSUE TITLE
Support for "connect" attribute of pyqtgraph PlotDataItem/PlotCurveItem?

### ISSUE THREAD

**Issue by nhansendev** [domarm-comat/pglive#15]
Per the [pyqtgraph documentation](https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/plotdataitem.html#pyqtgraph.PlotDataItem) it's possible to specify the connectivity of data points on a line plot via the `PlotDataItem`: 

```
connect supports the following arguments:

- ‘all’ connects all points.- 
- ‘pairs’ generates lines between every other point.- 
- ‘finite’ creates a break when a nonfinite points is encountered.- 
- If an ndarray is passed, it should contain N int32 values of 0 or 1. Values of 1 indicate that the respective point will be connected to the next.- 
- In the default ‘auto’ mode, PlotDataItem will normally use ‘all’, but if any nonfinite data points are detected, it will automatically switch to ‘finite’.
```
The `connect` arg is also found in the `PlotCurveItem.setData()` function.

Is this supported in pglive? I haven't found anything for it so far.

**Comment by domarm-comat** [comment]
`cb_append_data_point` and `cb_set_data` are passing all kwargs to `setData()`. Therefor you can use all pyqtgraph kwargs. In case of `connect` param, you can do it just by calling `cb_append_data_point(y, x, connect="pairs")`. Same for `cb_set_data`.

**Comment by nhansendev** [comment]
Thanks for clarifying that.
