### ISSUE TITLE
Custom ViewBox

### ISSUE THREAD

**Issue by Khanhlinhdang** [domarm-comat/pglive#20]
is ViewBox implemented? and How can I get the ViewBox? I jusst want to modify the wheelEvent, and some other Events? but I can find out the method? and can you add numpy array to the options of input data format, it is seem run well with small data, but with a lager it have been slow down and lag, i think with numpy array will be more fast then list like current.

**Comment by domarm-comat** [comment]
To answer first part of your question. You can get viewbox by calling `viewbox = plot.getViewBox()`. But if your aim is to modify mouse events, I would suggest to overload LivePlotWidget with your custom event handlers.
Here is an example (getting ViewBox is there as well):

```
import signal
from threading import Thread
import pglive.examples_pyqt5 as examples
from pglive.sources.data_connector import DataConnector
from pglive.sources.live_candleStickPlot import LiveCandleStickPlot
from pglive.sources.live_plot_widget import LivePlotWidget
from pyqtgraph import QtCore  # type: ignore

"""
In this example candlestick plot is displayed.
"""
class CustomLivePlotWidget(LivePlotWidget):

    def mouseMoveEvent(self, ev: QtCore.QEvent) -> None:
        super().mouseMoveEvent(ev)
        print("Mouse move:", ev.pos())

    def wheelEvent(self, ev):
        super().wheelEvent(ev)
        print("Mouse wheel:", ev.angleDelta())

win = CustomLivePlotWidget(title="Candlestick Plot @ 10Hz")
plot = LiveCandleStickPlot()
win.addItem(plot)

data_connector = DataConnector(plot, max_points=50, update_rate=10)

# Get viewbox
viewbox = plot.getViewBox()
print(viewbox)

win.show()

Thread(target=examples.candle_generator, args=(data_connector,)).start()
signal.signal(signal.SIGINT, lambda sig, frame: examples.stop())
examples.app.exec()
examples.stop()
```

Regarding second part of the question. I have to have a look at this. I'm not sure if the numpy array is limiting factor here. I would say it's the drawing part itself, as pglive is plotting all items every time plot is redrawn. Maybe there is some way to optimize it by caching some objects.  How many candles do you expect to plot in your app?

You may consider using [https://github.com/domarm-comat/pglive#plot-speed-optimizations](url) to limit number of candles by using `LiveAxisRange`.

I will get back to you with this. I'm a bit busy right now, so please be patient :).

**Comment by Khanhlinhdang** [comment]
Thank you much sir!
I did it. i create a custom viewbox, custom axis, and put them to a plotitem and then put plotitem into plotwidget. I can fully custom all of them. it is so good.

**Comment by domarm-comat** [comment]
That's good to hear! You're welcome :).

Do you still have issue with the performance or you manage to optimize it to your liking?

**Comment by Khanhlinhdang** [comment]
I am still doing with my project, I will report and ask you if i have a problem. Thank for your time!
