### ISSUE TITLE
Poetry Update

### ISSUE THREAD

**Issue by slartz42** [domarm-comat/pglive#25]
Sorry to bother you again, but would it be possible to update poetry so this will work with Python 3.11?

**Comment by domarm-comat** [comment]
No worries :). You're not the first one asking for Python 3.11 support. The reason it's not supported is, that I wanted to support Pyside2.
Unfortunately, Pyside2 is not compatible with P3.11. And on top of that, it seems, that developers are not maintaining Pyside2 package anymore.

I think now it's a good time to drop Pyside2 support and allow everyone to use modern Python versions.

I will do some testing and if everything works I will release version supporting 3.11 soon (possibly Tomorrow).

**Comment by slartz42** [comment]
That would be great, thanks!

**Comment by domarm-comat** [comment]
You should be able to run pglive 0.6.6 against Python3.11 now.

**Comment by slartz42** [comment]
It's installing now, thank you!
