### ISSUE TITLE
How to clear data from DataConnector?

### ISSUE THREAD

**Issue by veractor** [domarm-comat/pglive#26]
First off, cool project, I appreciate it!

I was trying to clear a graph that already had some existing data with a particular `DataConnector` that has a finite `max_points`, but I've tried setting the data using empty lists and it keeps complaining that `NoneType`s are not subscriptable.

After reading the code a bit, I tried to clear the data with `cb_set_data` using 2 empty deques with my desired `maxlen` like this:
```python
self.data_connector.cb_set_data(deque(maxlen=self.max_samples), deque(maxlen=self.max_samples))
```

But it still complained about the same problem.

Am I missing a way to clear plot data?

**Comment by domarm-comat** [comment]
Hey, thanks for your interest in pglive and for your valuable feedback!

Yes, you're right. There is no easy way to reset data. Certainly not via `DataConnector`. It's very valid request and missing feature of pglive.

Give me one or two days and I will release version which will support clearing plot using `DataConnector`.

**Comment by domarm-comat** [comment]
It took me a bit longer, than I anticipated. But now you should be able to use `clear` method in `DataConnector` to clear plot data. Please have a look at the latest release v0.6.7.

**Comment by veractor** [comment]
Nice! It works well for my purposes. Thank you for the prompt response!
