### ISSUE TITLE
Crosshair label not formatted

### ISSUE THREAD

**Issue by optio50** [domarm-comat/pglive#3]
Not sure if its a bug or simply requires proper formatting on my part.
Using bottom_axis = LiveAxis("bottom", **{Axis.TICK_FORMAT: Axis.TIME})
the X crosshair is displayed in raw unformatted epoch time.

Can you suggest a way to format the X crosshair label when using tick format Time?

thank you

**Comment by domarm-comat** [comment]
It's kind of a bug. Crosshair is using method `x_format` of `LivePlotWidget` to determine tick string. And `LiveAxis` is using `tickStrings` method to format a string in DATETIME or TIME. To solve this `x_format` method should check if Axis X ot Y is instance of `LiveAxis` and use its formatter.
I will have a look and fix this issue. I'm a quite busy right now, but try to fix it as soon as possible :).
Thanks for Your help and patience.

**Comment by optio50** [comment]
Thanks for the attention you put into this project.
No Hurry. I understand.

**Comment by domarm-comat** [comment]
I've found some time Today to fix Your issue. Try new version 0.2.4, crosshair tick format should be fixed and match LiveAxis.

**Comment by optio50** [comment]
Indeed, X Axis crosshair label displays correctly. :-)
You're awesome!

Thanks!

**Comment by domarm-comat** [comment]
Glad it works for You.
You're welcome :)!
