### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (2,) (0,)

### ISSUE THREAD

**Issue by optio50** [domarm-comat/pglive#32]
Hello, It's been awhile and working fine until I upgraded today to Ubuntu 22.04.3 LTS Jammy
Reinstalled Pglive and Pyqtgraph
No program changes have been made and now have an error when charts are updating.

> Traceback (most recent call last):
  File "/home/chromebox/.local/lib/python3.10/site-packages/pglive/sources/live_mixins.py", line 45, in slot_roll_tick
    self.plot_widget.slot_roll_tick(data_connector, tick)
  File "/home/chromebox/.local/lib/python3.10/site-packages/pglive/sources/live_plot_widget.py", line 215, in slot_roll_tick
    final_x_range = self.x_range_controller.get_x_range(data_connector, tick)
  File "/home/chromebox/.local/lib/python3.10/site-packages/pglive/sources/live_axis_range.py", line 30, in get_x_range
    axis_range = [0, data_connector.plot.data_tick(ax=0)]
  File "/home/chromebox/.local/lib/python3.10/site-packages/pglive/sources/live_categorized_bar_plot.py", line 126, in data_tick
    if self.x_data == []:
ValueError: operands could not be broadcast together with shapes (2,) (0,)

**Comment by optio50** [comment]
0.6.6 is the last version thats works for my code.
After that the rolling display breaks and the categorized bar charts lose the labels and dont have any data.
Also the time ticks are not displaying the correct time.

**Comment by domarm-comat** [comment]
Hey Optio, I'm sorry to hear that things are not working for you.
I believe it's due to the recent updates, I had to do to fix other issues people had.

I tested again against all the examples and categorized_bar_plot.py is working nicely for me. Could you try if at least pglive examples are working for you?

Can you please give me example of your input, which casuses the ValueError?

Also time tick input data and what is your faulty output and expected output.

I'm a bit short on time, since past few weeks.
But I will look at it as soon as you will give me some starting point and test data.

**Comment by optio50** [comment]
Thanks for looking into it.
I am also a bit short on time for awhile.
I can use 0.6.6 until I figure something out so no hurry. :-)
Thanks again for a really cool live chart!

**Comment by optio50** [comment]
It seems there is an additional error. I think I had  0.6.7 installed when I posted the first errors. 
Now 7.1 is installed and I also see this. ValueError: year 33658 is out of range

Edit: I was mistaken about the other error. Typo caused.

This one still applies

> Traceback (most recent call last):
  File "/home/chromebox/.local/lib/python3.10/site-packages/pglive/sources/live_mixins.py", line 45, in slot_roll_tick
    self.plot_widget.slot_roll_tick(data_connector, tick)
  File "/home/chromebox/.local/lib/python3.10/site-packages/pglive/sources/live_plot_widget.py", line 215, in slot_roll_tick
    final_x_range = self.x_range_controller.get_x_range(data_connector, tick)
  File "/home/chromebox/.local/lib/python3.10/site-packages/pglive/sources/live_axis_range.py", line 32, in get_x_range
    axis_range = data_connector.plot.data_bounds(ax=0, offset=self.roll_on_tick if self.roll_on_tick > 1 else 0)
  File "/home/chromebox/.local/lib/python3.10/site-packages/pglive/sources/live_categorized_bar_plot.py", line 116, in data_bounds
    if self.x_data == []:
ValueError: operands could not be broadcast together with shapes (5,) (0,)

**Comment by sowen80** [comment]
Hi all! Love what you've done for us here! I also am experiencing this issue with live_categorized_bar_plot objects. Exactly the same error and also receiving the error using the pyside6 example code.

Some additional info below:
Running on Windows 11 Home 22H2

Python 3.11.0

Package            Version
------------------ ------------
numpy              1.26.0
pandas             2.1.1
pglive             0.7.1
pip                23.1.1
pyqtgraph          0.13.3
pyserial           3.5
PySide6            6.5.2
PySide6-Addons     6.5.2
PySide6-Essentials 6.5.2
python-dateutil    2.8.2
pytz               2023.3.post1
setuptools         67.7.1
shiboken6          6.5.2
six                1.16.0
tzdata             2023.3
wheel              0.40.0

**Comment by pwspen** [comment]
I have been chasing this down for a few days and found that it is a compatibility issue with Numpy version 1.25 and above. 1.24.3 is the last version that does not throw an error when you import numpy and do x == y with x and y being arrays of a different shape. I think that replacing all instances of array comparison with numpy imported with np.array_equal(x, y) should fix this but haven't confirmed yet.

**Comment by domarm-comat** [comment]
Hi everyone. Thanks for looking into this issue. I can confirm, that this issue is related to Numpy update as @pwspen find out. Now I can replicate it on my end as well. Thanks for your patience. I know the updates are coming in slower pace than usual. I will be looking into it this week and hopefuly have a fix soon.

**Comment by domarm-comat** [comment]
Could you please try if updated code in branch: [issue_32_fix](https://github.com/domarm-comat/pglive/tree/issue_32_fix) fixed this issue for everyone?

**Comment by pwspen** [comment]
The error is no longer being thrown but it broke LivePlotWidget.setRange() for me, instead my graphs are just auto-scaling.

**Comment by domarm-comat** [comment]
@pwspen could you provide me with some example data / code, so I can reproduce your error easilly? I'm trying against [live_plot_range.py](https://github.com/domarm-comat/pglive/blob/main/pglive/examples_pyside6/live_plot_range.py) and it works fine after the fix.

**Comment by pwspen** [comment]
I think I might not be using the intended way to disable auto scaling and show a fixed range. What is the best way to make a liveVbarplot fixed-range?

**Comment by pwspen** [comment]
Nevermind, the problem was between the keyboard and chair, working wonderfully now. Thanks for the quick fix, this library has been very useful for me, I've wrangled with matplotlib liveplotting and it is complicated and slow and difficult to integrate into GUIs, but pglive basically just works, it's great.

**Comment by domarm-comat** [comment]
No worries :). Most important thing is, that evertyhing is working for you. Feel free to suggest any improvements you might consider being helpful for you. I would love to see this package improve and help others with their work or hobbies.

Ok as nobody else is complaining :), I will merge this fix and release new version.
I will leave it to @optio50 to close this issue once he confirm things are working for him as well.

**Comment by optio50** [comment]
The error as described in this issue seems to be resolved. 
Thank you.
I still have what appears to be a Roll on Tick issue that I will address in the other open issue or a new one if different.
Thank you for your work! :-)
