### ISSUE TITLE
Bug or Feature? LivePlotWidget "bottom" axis ticks labels disappear if string is more than simple one liner

### ISSUE THREAD

**Issue by PhysicsGuyBrian** [domarm-comat/pglive#37]
Hello,
First, thank you for pglive.   DataConnector is very cool!

To determine if pglive will work for my project needs,  I am trying to implement your LivePlotWidget with a barchart such that the bottom axis labels are like those shown below from another plotter I wrote just using pyqtgraph.  

![image](https://github.com/domarm-comat/pglive/assets/3181310/ddce22c4-19e2-4d36-ac14-d35e324439c5)

However, LivePlotWidget refuses to show any tick labels if the string has more than two vertical elements. 

For context,  I am building the bottom axis in the image above using simple string formatting like so...
`
listOfBottomTuples = [ [ (i, '\n%s\n↑ %d,%d\nμ %d,%d\n↓ %d,%d\nσ  %d,%d\n' %  (str(i),aLMax,aUMax,aLMean,aUMean,aLMin,aUMin,aLStd,aUStd)  if i == 1 else 
 '\n%s\n%d,%d\n%d,%d\n%d,%d\n%d,%d\n' %  (str(i),aLMax,aUMax,aLMean,aUMean,aLMin,aUMin,aLStd,aUStd)) for 
 i,aLMax,aUMax,aLMean,aUMean,aLMin,aUMin,aLStd,aUStd in values ] ]  
`
It's brute force but works just fine for a plotter that updates once per second in the other plotter tool I wrote.

I can create a simple list of tuples containing channel numbers and that works just fine.  But  it does not like more than that as labels and it appears that the space between the tick labels and axis label is fixed.  Below is my implementation of your LivePlotWidget where you can see the most I can put in the tick labels before it shows nothing.  It just so happens that the tick labels are just down to where the axis label 'Lane' sits.  

![image](https://github.com/domarm-comat/pglive/assets/3181310/9f9c4ff9-37a7-48ad-a56b-8c7e4e61bb48)

When it refuses, it looks like this...

![image](https://github.com/domarm-comat/pglive/assets/3181310/996776ea-488d-49ef-9cdf-7a54f142f040)

Am I incorrect in thinking that the space between tick labels and axis label should grow automatically like it does in pyqtgraph native plotWidget?  If this is not a bug and instead just me being an idiot, then please point me in the right direction.  

Thank you in advance.
Brian

**Comment by domarm-comat** [comment]
Sorry for super late reply to your question. Tick handling is quite "tricky". As I wanted to support plotting ticks at different angles, I overrode pyqtgraph code, that renders ticks. That code was not supporting multine ticks.
Please, try `v0.7.7`, it should hopefully fix your issues.
If you encouter some spacing problem (bottom of the tick clipped) add one additional empty line `\n` to the tick.
