### ISSUE TITLE
Adjusting text in vertical leading lines 

### ISSUE THREAD

**Issue by axshb** [domarm-comat/pglive#41]
I wanted to adjust the rotation and color of text with a vertical leading line. As far as I'm aware, this isn't possible in its current implementation (correct me if I'm wrong about this). I’ve made some rough changes to get this working, but a more complete solution would be ideal. 

The modifications I've made work for my use case involving 2 digit numbers at most. I suspect the text would clip out of view with lengthier figures though.

Here are my modifications to the `MixinLeadingLine` class:

in `set_leading_line`:
- Added parameters for text color and text rotation
```python
def set_leading_line(self, orientation: str = LeadingLine.VERTICAL,
        pen: QtGui.QPen = None, text_axis: str = LeadingLine.AXIS_X, 
        text_color: str = "black", text_rotation: float = -90,  **kwargs) -> Dict:
        text_axis = text_axis.lower()
        assert text_axis in (LeadingLine.AXIS_X, LeadingLine.AXIS_Y)

        self.sigPlotChanged.connect(self.update_leading_line)

        if pen is None:
            pen = self.opts.get("pen")
        if orientation == LeadingLine.VERTICAL:
            _v_leading_line = pg.InfiniteLine(angle=90, movable=False, pen=pen)
            _v_leading_text = pg.TextItem(color=text_color, angle=text_rotation, fill=pen.color())
            _v_leading_line.setZValue(999)
            _v_leading_text.setZValue(999)
            self._vl_kwargs = {"line": _v_leading_line, "text": _v_leading_text, "pen": pen, "text_axis": text_axis,
                               "text_color": text_color, "text_rotation": text_rotation, **kwargs}
            return self._vl_kwargs
        elif orientation == LeadingLine.HORIZONTAL:
            _h_leading_line = pg.InfiniteLine(angle=0, movable=False, pen=pen)
            _h_leading_text = pg.TextItem(color=text_color, fill=pen.color())
            _h_leading_text.setZValue(999)
            _h_leading_text.setZValue(999)
            self._hl_kwargs = {"line": _h_leading_line, "text": _h_leading_text, "pen": pen, "text_axis": text_axis,
                               "text_color": text_color, "text_rotation": text_rotation, **kwargs}
            return self._hl_kwargs
        else:
            raise TypeError("Unsupported LeadingLine type")
```
in `update_leading_text`:
- Adjusted the positioning of the text to accommodate non-rotated text
```python
if self._vl_kwargs is not None:
      text_axis = x_text if self._vl_kwargs["text_axis"] == LeadingLine.AXIS_X else y_text
      text_item = self._vl_kwargs["text"]
      text_item.setText(text_axis)
      text_item.setAnchor((0.5, 0))
      pixel_pos = vb.mapViewToScene(QtCore.QPointF(x, y))
      y_pos = 0 + self._vl_kwargs["text"].boundingRect().height() + 5
      new_pos = vb.mapSceneToView(QtCore.QPointF(pixel_pos.x(), y_pos))
      self._vl_kwargs["text"].setPos(new_pos.x(), new_pos.y())
``` 

Here are what the changes look like:
![Untitled](https://github.com/user-attachments/assets/87fc57c7-1938-4347-9feb-5408c7375e78)

Ideally, I’d have the text sit on the left side of the leading line instead, and have it expand further left  if/when it lengthens.

**Comment by domarm-comat** [comment]
Hey! Sorry for late reply.

I add option (v0.7.6) to change text color and orientation of the leading line label.
You can now use this code to achieve what you need:
`plot.set_leading_line(LeadingLine.VERTICAL, pen=mkPen("red"), text_axis=LeadingLine.AXIS_Y, text_color="white",
                      text_orientation=Orientation.HORIZONTAL)`

You can try updated [leading line lexample](https://github.com/domarm-comat/pglive/blob/main/pglive/examples_pyqt6/leading_line.py) to see if it's working for you.
