### ISSUE TITLE
Question in adding new live stream data

### ISSUE THREAD

**Issue by MichaelMa1996** [domarm-comat/pglive#6]
Is there a way to add multiple different live data streams in a for loop? Instead of manually defining each live data stream by a DataConnector?

**Comment by domarm-comat** [comment]
Purpose of DataConnector is to manage appending or setting new data and ensure thread-safe plotting. You are not attaching any example so it's harder for me to answer your question.

In current implementation you have one DataConnector per LivePlot to keep it simple.
Assuming you have one stream of data connected per LivePlot, this is sufficient.
In order for DataConnector to work, you have to call callbacks to feed it with data. This must be done by your application. You can of course generate LivePlots with it's connectors in a loop. No problem doing so.
If you need something very specific, you can always re-implement DataConnector class with different parameters to suit your needs.
There are also other ways to ensure thread-safe execution, for example using QThread or QTimer to safely update plot, but I found easiest to do and understand by using DataConncetor.

If this doesn't answer your question, please show some example of your problem and I will try to answer it.
